### ISSUE TITLE
When a bonus is 'Optional', its modifications should be optional, not simply its additive bonuses

### ISSUE THREAD

**Issue by krbz999** [krbz999/babonus#363]
Currently a system limitation. Possibly resolved fully with ~~v3.1~~ ~~v3.2~~ ~~v3.3~~ ~~v4.0~~ v4.1.

Technically breaking as it changes the current behavior, though the new behavior would be more intuitive.

- [x] #450
- [x] #451
- [ ] When an attack babonus is optional, all its modifications should be optional.
- [ ] When a saving throw babonus is optional, all its modifications should be optional.
- [ ] When a check babonus is optional, all its modifications should be optional.
- [ ] When a save dc babonus is optional, all its modifications should be optional.
- [x] #470 
- [x] #471 
- [ ] #472

**Comment by krbz999** [comment]
Sadly not resolved by 3.2.

**Comment by krbz999** [comment]
Not resolved with 3.3 either.

**Comment by krbz999** [comment]
Not resolved with 4.0.

But Arbron pinky-swears it'll happen in 4.1.
