### ISSUE TITLE
Feature: Improved accommodation of grid types and measurement options

### ISSUE THREAD

**Issue by krbz999** [krbz999/babonus#86]
A tentative issue for future improvements. Comments are welcomed.

The way that auras are displayed will need to be redone for the v12 grid api.
This likely also involves enhancing, or entirely doing away with, some of the module's API methods.

- [x] Add option to use grid spaces when calculating distance. This would by default respect the measuring system (5/5/5 or 5/10/5) set in the system settings. (#56)
- [x] Add option to _not_ increase the radius of an aura to match the size of its owner's token. (#56)
- [x] ~~Investigate if aura ranges need tweaking on hex grids.~~
- [x] ~~Investigate if aura ranges need tweaking on gridless scenes.~~
- [x] ~~When calculating distance, create an option to calculate the Euclidean distance, rather than simplified metrics of a hypotenuse.~~
- [x] Ensure that aura previews match the customized aura range.

**Comment by krbz999** [comment]
Also blocked, same as #56.

**Comment by krbz999** [comment]
Most of the points here have been solved by the v12 grid API.

**Comment by krbz999** [comment]
With changes to the canvas API in v12, aura ranges will simply *always* be measured in grid spaces.

**Comment by krbz999** [comment]
Due to the default way that the canvas ruler now functions on gridded scenes, an option is added that can toggle padding of the aura ranges *only* on gridless scenes.
